# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ddd3e8e4d0709c2ee722dd7bd92f63ba6fcfd8b7674aa9084018dd2386e00da8889ba799bcb6e1e7f02857a53b7f170040d6703f77e561c0286e8fb5b4b580b

test:
  secret_key_base: 53b6a5024e0db53d992d56d5b6905c005b25e2a3c1fff3352349d7234142caf36dc94d97d3f1c870f81745b89c043ae84af777cf42a6efc642a5e8ad5a002391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
